/** Piano-roll styles, scoped under .dsh-roll-* class names. */
export const CSS = [
  '.dsh-midi-caption { font-size: 11px; color: #9a9aa2; margin-top: 6px; }',
  '.dsh-midi-error { font-size: 12px; color: #d05a5a; }',
  '.dsh-roll-toolbar { display: flex; align-items: center; gap: 6px; margin-bottom: 6px; }',
  '.dsh-roll-btn { background: #26262e; color: #d0d0d8; border: 1px solid #34343e; border-radius: 4px; font-size: 12px; line-height: 1; padding: 5px 9px; cursor: pointer; }',
  '.dsh-roll-btn:hover { background: #30303a; }',
  '.dsh-roll-zoomslider { display: inline-flex; align-items: center; gap: 4px; font-size: 11px; color: #9a9aa2; }',
  '.dsh-roll-zoomslider input[type=range] { width: 120px; cursor: pointer; }',
  '.dsh-roll-select { background: #26262e; color: #d0d0d8; border: 1px solid #34343e; border-radius: 4px; font-size: 12px; padding: 4px 6px; cursor: pointer; max-width: 160px; }',
  '.dsh-roll { position: relative; height: 360px; background: #17171b; border: 1px solid #2a2a30; border-radius: 8px; overflow: hidden; user-select: none; cursor: grab; touch-action: none; }',
  '.dsh-roll.dsh-dragging { cursor: grabbing; }',
  '.dsh-roll-keyboard { position: absolute; left: 0; top: 0; bottom: 0; width: 68px; overflow: hidden; background: #1d1d22; z-index: 2; border-right: 1px solid #2a2a30; }',
  '.dsh-roll-keys { position: absolute; left: 0; top: 0; width: 68px; transform-origin: 0 0; }',
  '.dsh-roll-canvas { position: absolute; left: 68px; top: 0; bottom: 0; right: 0; overflow: hidden; background: #141419; }',
  '.dsh-roll-world { position: absolute; left: 0; top: 0; transform-origin: 0 0; }',
  '.dsh-roll-key { position: absolute; left: 0; right: 0; box-sizing: border-box; border-bottom: 1px solid rgba(0,0,0,0.35); }',
  '.dsh-roll-key.dsh-white { background: #e8e8ec; }',
  '.dsh-roll-key.dsh-black { background: #101014; }',
  '.dsh-roll-keylabel { position: absolute; left: 6px; bottom: 1px; font-size: 9px; line-height: 1; color: #8a8a94; pointer-events: none; }',
  '.dsh-roll-key.dsh-black .dsh-roll-keylabel { color: #f0f0f2; }',
  '.dsh-roll-note { position: absolute; border-radius: 3px; opacity: 0.92; box-shadow: inset 0 -2px 0 rgba(0,0,0,0.25); }',
  '.dsh-roll-grid-v { position: absolute; top: 0; bottom: 0; width: 1px; background: rgba(255,255,255,0.05); }',
  '.dsh-roll-grid-v.dsh-bar { width: 2px; background: rgba(255,255,255,0.14); }',
  '.dsh-roll-grid-h { position: absolute; left: 0; right: 0; height: 1px; background: rgba(255,255,255,0.04); }',
].join('')
